@startuml
'https://plantuml.com/class-diagram

abstract class Shape {
    -shapeName: String
    +Shape()
    +Shape(shapeName: String)
    +void setShapeName(String:shapeName)
    +string getShapeName()
}
class Rectangle extends Shape{
    -length: double
    -width: double
    +Rectangle()
    +Rectangle(length: double, width: double)
    +void setLength(length: double)
    +void setWidth(width: double)
    +double getLength()
    +double getWidth()
    +String toString()
    +void askMeasurements()
    +double calcArea()
}

class Parallelogram extends Shape {
    -base: double
    -height: double
    +Parallelogram()
    +Parallelogram(base: double, height: double)
    +void setBase(base: double)
    +void setHeight(height: double)
    +double getBase()
    +double getHeight()
    +String toString()
    +void askMeasurements()
    +double calcArea()
}
class Circle extends Shape {
    -radius: double
    +Parallelogram()
    +Parallelogram(radius: double)
    +void setRadius(radius: double)
    +double getRadius()
    +String toString()
    +void askMeasurements()
    +double calcArea()
}

class ShapeDriver {
    +main(String[] args)
}


@enduml